---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image:  mohanudayana/web:app-image
   ports:
     - "3306:3306"

 application:
   image:  mohanudayana/web:db-image
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
